# coding: utf-8
quotes = [
    'Hahahahaha. Oh wait you\'re serious. Let me laugh even harder.',
    'Anything less than immortality is a complete waste of time.',
    'Let\'s go alredaaaayyy!',
    'Some day we\'ll be able to look back on this whole thing and laugh...'
    'AH HA HA HA!!!!',
    'It\'s not my fault.',
    'Do. Or do not. There is no try.',
    'I\'ve got a bad feeling about this.',
    'Your eyes can deceive you. Don\'t trust them.',
    'Stay on target.',
    'This is a new day, a new beginning.',
    'May the Force be with you',
    'Use the force, Luke.',
    'Mmm. Lost a planet, Master Obi-Wan has. How embarrassing.',
    'If there\'s a bright centre to the universe, '
    'you\'re on the planet that it\'s farthest from.',
    'Fear is the path to the dark side.',
    'I find your lack of faith disturbing.',
    'There\'s always a bigger fish.',
    'Hello. I don\'t believe we have been introduced. R2-D2? '
    'A pleasure to meet you. I am C-3PO, Human-Cyborg Relations.',
    'Ahh, hard to see, the Dark Side is.',
    'Sir, the possibility of successfully navigating an asteroid field '
    'is approximately 3,720 to 1.',
    'Obi-Wan has taught you well.',
    'I suggest a new strategy, R2: let the Wookiee win.',
    'Remember...the Force will be with you, always.',
    'Don\'t Panic!',
    'Would it save you a lot of time if I just gave up and went mad now?',
    'You\'re turning into a penguin. Stop it.',
    'So long, and thanks for all the fish.',
    'All those moments will be lost in time… like tears in rain.',
    'Bond. James Bond.',
    'Do I look like I give a damn?',
    'Everybody runs, Fletch.',
    'Fasten your seat belts, it\'s going to be a bumpy night!',
    'Go ahead, make my day.',
    'I am Groot',
    'I drink your milkshake!',
    'I\'ll be back.',
    'I\'m gonna make him an offer he can\'t refuse.',
    'In case I don\'t see ya, good afternoon, good evening, and good night!',
    'Just keep swimming.',
    'Life is a box of chocolates, Forrest. '
    'You never know what you\'re gonna get.',
    'Louis, I think this is the beginning of a beautiful friendship.',
    'Nobody\'s perfect.',
    'To infinity… and beyond.',
    'Why so serious?',
    "Two wrongs don't make a right.",
    "The pen is mightier than the sword.",
    "When in Rome, do as the Romans.",
    "The squeaky wheel gets the grease.",
    "When the going gets tough, the tough get going.",
    "No man is an island.",
    "Fortune favors the bold.",
    "People who live in glass houses should not throw stones.",
    "Better late than never.",
    "Birds of a feather flock together.",
    "Keep your friends close and your enemies closer."
    "A picture is worth a thousand words.",
    "There's no place like home.",
    "Discretion is the greater part of valor.",
    "The early bird catches the worm.",
    "Never look a gift horse in the mouth.",
    "You can't make an omelet without breaking a few eggs.",
    "God helps those who help themselves.",
    "A watched pot never boils.",
    "Beggars can't be choosers.",
    "Actions speak louder than words.",
    "If it ain't broke, don't fix it.",
    "Practice makes perfect.",
    "Too many cooks spoil the broth.",
    "Easy come, easy go.",
    "If you can't beat 'em, join 'em.",
    "There's no time like the present.",
    "Beauty is in the eye of the beholder.",
    "Necessity is the mother of invention.",
    "A penny saved is a penny earned.",
    "Familiarity breeds contempt.",
    "You can't judge a book by its cover.",
    "Good things come to those who wait.",
    "Don't put all your eggs in one basket.",
    "Two heads are better than one.",
    "The grass is always greener on the other side of the hill.",
    "Do unto others as you would have them do unto you.",
    "A chain is only as strong as its weakest link.",
    "Honesty is the best policy.",
    "You can lead a horse to water, but you can't make him drink.",
    "Don't count your chickens before they hatch.",
    "If you want something done right, you have to do it yourself.",
    "Houston, we have a problem.",
    "Elementary, my dear Watson.",
    "Is it safe?",
    "My precious.",
    "I feel the need — the need for speed!",
    "A martini. Shaken, not stirred.",
]
