# coding: utf-8
quotes = [
    'Hahahahaha. Oh wait you\'re serious. Let me laugh even harder.',
    'Anything less than immortality is a complete waste of time.',
    'Let\'s go alredaaaayyy!',
    'Some day we\'ll be able to look back on this whole thing and laugh...'
    'AH HA HA HA!!!!',
    'It\'s not my fault.',
    'Do. Or do not. There is no try.',
    'I\'ve got a bad feeling about this.',
    'Your eyes can deceive you. Don\'t trust them.',
    'Stay on target.',
    'This is a new day, a new beginning.',
    'May the Force be with you',
    'Use the force, Luke.',
    'Mmm. Lost a planet, Master Obi-Wan has. How embarrassing.',
    'If there\'s a bright centre to the universe, '
    'you\'re on the planet that it\'s farthest from.',
    'Fear is the path to the dark side.',
    'I find your lack of faith disturbing.',
    'There\'s always a bigger fish.',
    'Hello. I don\'t believe we have been introduced. R2-D2? '
    'A pleasure to meet you. I am C-3PO, Human-Cyborg Relations.',
    'Ahh, hard to see, the Dark Side is.',
    'Sir, the possibility of successfully navigating an asteroid field '
    'is approximately 3,720 to 1.',
    'Obi-Wan has taught you well.',
    'I suggest a new strategy, R2: let the Wookiee win.',
    'Remember...the Force will be with you, always.',
    'Don\'t Panic!',
    'Would it save you a lot of time if I just gave up and went mad now?',
    'You\'re turning into a penguin. Stop it.',
    'So long, and thanks for all the fish.',
    'All those moments will be lost in time… like tears in rain.',
    'Bond. James Bond.',
    'Do I look like I give a damn?',
    'Everybody runs, Fletch.',
    'Fasten your seat belts, it\'s going to be a bumpy night!',
    'Go ahead, make my day.',
    'I am Groot',
    'I drink your milkshake!',
    'I\'ll be back.',
    'I\'m gonna make him an offer he can\'t refuse.',
    'In case I don\'t see ya, good afternoon, good evening, and good night!',
    'Just keep swimming.',
    'Life is a box of chocolates, Forrest. '
    'You never know what you\'re gonna get.',
    'Louis, I think this is the beginning of a beautiful friendship.',
    'Nobody\'s perfect.',
    'To infinity… and beyond.',
    'Why so serious?',
    "Two wrongs don't make a right.",
    "The pen is mightier than the sword.",
    "When in Rome, do as the Romans.",
    "The squeaky wheel gets the grease.",
    "When the going gets tough, the tough get going.",
    "No man is an island.",
    "Fortune favors the bold.",
    "People who live in glass houses should not throw stones.",
    "Better late than never.",
    "Birds of a feather flock together.",
    "Keep your friends close and your enemies closer."
    "A picture is worth a thousand words.",
    "There's no place like home.",
    "Discretion is the greater part of valor.",
    "The early bird catches the worm.",
    "Never look a gift horse in the mouth.",
    "You can't make an omelet without breaking a few eggs.",
    "God helps those who help themselves.",
    "A watched pot never boils.",
    "Beggars can't be choosers.",
    "Actions speak louder than words.",
    "If it ain't broke, don't fix it.",
    "Practice makes perfect.",
    "Too many cooks spoil the broth.",
    "Easy come, easy go.",
    "If you can't beat 'em, join 'em.",
    "There's no time like the present.",
    "Beauty is in the eye of the beholder.",
    "Necessity is the mother of invention.",
    "A penny saved is a penny earned.",
    "Familiarity breeds contempt.",
    "You can't judge a book by its cover.",
    "Good things come to those who wait.",
    "Don't put all your eggs in one basket.",
    "Two heads are better than one.",
    "The grass is always greener on the other side of the hill.",
    "Do unto others as you would have them do unto you.",
    "A chain is only as strong as its weakest link.",
    "Honesty is the best policy.",
    "You can lead a horse to water, but you can't make him drink.",
    "Don't count your chickens before they hatch.",
    "If you want something done right, you have to do it yourself.",
    "Houston, we have a problem.",
    "Elementary, my dear Watson.",
    "Is it safe?",
    "My precious.",
    "I feel the need — the need for speed!",
    "A martini. Shaken, not stirred.",
    "It worked yesterday",
    "I'm surprised it works as well as it does",
    "It's just some unlucky coincidence",
    "I didn't receive a ticket for it",
    "I haven't touched that code in weeks",
    "I'm still working on that as we speak",
    "It works, but it's not been tested",
    "Always code as if the guy who ends up maintaining your code will "
    "be a violent psychopath who knows where you live.",
    "A good programmer looks both ways before crossing a one-way street.",
    "Hey! It compiles! Ship it!",
    "I have NOT lost my mind—I have it backed up on tape somewhere.",
    "It works on my machine.",
    "Only half of programming is coding. The other 90% is debugging.",
    "Press any key to continue or any other key to quit.",
    "The best thing about a boolean is even if you are wrong, you are "
    "only off by a bit.",
    "The nice thing about standards is that there are so many to choose from.",
    "There is nothing quite so permanent as a quick fix.",
    "There\'s no test like production.",
    "I love deadlines. I like the whooshing sound they make as they fly by.",
    "I think we agree, the past is over.",
    "In the future everyone will be famous for fifteen minutes.",
    "In three words I can sum up everything I\'ve learned about life: "
    "it goes on.",
    "It is a mistake to think you can solve any major problems just "
    "with potatoes.",
    "Just don\'t create a file called -rf.",
    "Let\'s call it an accidental feature.",
    "Measuring programming progress by lines of code is like measuring "
    "aircraft building progress by weight.",
    "Nobody expects the Spanish inquisition.",
    "On the Internet, nobody knows you\'re a dog.",
    "Did you know? Perl - The only language that looks the same "
    "before and after RSA encryption.",
    "Stay hungry, stay foolish.",
    "The problem with troubleshooting is that trouble shoots back.",
    "Time is an illusion. Lunchtime doubly so.",
    "When in doubt, leave it out.",
    "Sometimes it pays to stay in bed on Monday, rather than spending "
    "the rest of the week debugging Monday\'s code.",
    "You miss 100 percent of the shots you never take.",
    "Inside every large program, there is a program trying to get out.",
    "Why do we never have time to do it right, but always have time to "
    "do it over?",
    "The goal of Computer Science is to build something that will last "
    "at least until we\'ve finished building it.",
    "Reality itself is too obvious to be true.",
    "Let me just change this one line of code…",
    "Fast, Good, Cheap. Pick two.",
    "Did you know? The collective noun for a group of programmers is "
    "a merge-conflict.",
    "A person who never made a mistake never tried anything new.",
    "If the facts don\'t fit the theory, change the facts.",
    "I only believe in statistics that I doctored myself.",
    "If you\'re going through hell, keep going.",
    "I have never let my schooling interfere with my education.",
    "The secret of getting ahead is getting started.",
    "Apparently there is nothing that cannot happen today.",
    "The best way to make your dreams come true is to wake up.",
    "People that hate cats will come back as mice in their next life.",
    "Sometimes I think we\'re alone in the universe & sometimes I "
    "think we\'re not. In either case the idea is quite staggering",
    "Talk is cheap, show me the code!",
    "They did not know it was impossible, so they did it!",
    "You want it in one line? Does it have to fit in 80 columns?",
    "The Internet? Is that thing still around?",
    "The journey is the destination.",
    "The older I get, the more I believe that the only way to "
    "become a better programmer is by not programming.",
    "Good is the enemy of great, but great is the enemy of shipped.",
    "Simplicity is prerequisite for reliability.",
    "No one hates software more than software developers.",
    "Code is like humor. When you have to explain it, it\'s bad.",
    "Code never lies, comments sometimes do.",
]
